site_name: morethemes
site_url: https://josephbarbierdarnal.github.io/morethemes/
repo_url: https://github.com/JosephBARBIERDARNAL/morethemes
theme:
  name: material
  features:
    - content.code.copy
    - content.tabs.link
  icon:
    repo: fontawesome/brands/github

nav:
  - Home: index.md
  # - Gallery: gallery.md
  - Create a theme: create-a-theme.md
  - Contributing: contributing.md

markdown_extensions:
  - pymdownx.tabbed:
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
