site_name: morethemes
site_url: https://josephbarbierdarnal.github.io/morethemes/
repo_url: https://github.com/JosephBARBIERDARNAL/morethemes
theme:
  name: material
  features:
    - content.code.copy
  icon:
    repo: fontawesome/brands/github

nav:
  - Home: index.md
  - Create a theme: create-a-theme.md
  - Contributing: contributing.md

extra:
  analytics:
    provider: google
    property: G-XXXXXXXXXX

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences