[project]
name = "morethemes"
version = "0.1.0"
description = "More themes for matplotlib"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.0",
    "pre-commit>=4.0.1",
]

[dependency-groups]
dev = [
    "pytest>=8.3.4",
]
